# HOST 2: Order Service
services:
  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    volumes:
      - ./order-db:/app/data
    environment:
      - GATEWAY_URL=http://HOST1_IP  # Change to Host 1 IP
